SET @SCORE=70
SELECT
CASE
WHEN @SCORE >= 90 AND @SCORE <= 100 THEN
'优秀'
WHEN @SCORE >= 80 AND @SCORE <= 90 THEN
'良好'
WHEN @SCORE >= 70 AND @SCORE <= 80 THEN
'中'
WHEN @SCORE >= 60 AND @SCORE <= 70 THEN
'及格'
WHEN @SCORE <= 60 THEN
'不及格'
END;
